In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2025s2-inter-uni-datathon/visitation_data.csv
/kaggle/input/2025s2-inter-uni-datathon/climate_data.csv
/kaggle/input/2025s2-iud-pre-processed-data/final_dataset.csv

In [2]:
FILE = "/kaggle/input/2025s2-iud-pre-processed-data/final_dataset.csv"
climate = pd.read_csv(FILE)

climate

,Year,SkiWeek,Resort,Visitors,Maximum temperature (Degree C),Minimum temperature (Degree C),Rainfall amount (millimetres)
0,2014,1,Mt. Baw Baw,555,4.957143,1.100000,24.4
1,2014,2,Mt. Baw Baw,804,5.485714,0.814286,21.0
2,2014,3,Mt. Baw Baw,993,1.042857,-1.814286,76.4
3,2014,4,Mt. Baw Baw,2976,2.528571,-0.957143,82.0
4,2014,5,Mt. Baw Baw,11112,0.685714,-2.257143,82.6
...,...,...,...,...,...,...,...
1262,2024,11,Charlotte Pass,2667,4.900000,-0.307143,29.6
1263,2024,12,Charlotte Pass,2392,3.542857,-0.250000,85.2
1264,2024,13,Charlotte Pass,1323,6.300000,-0.014286,32.3
1265,2024,14,Charlotte Pass,454,7.414286,-0.985714,11.5
1266,2024,15,Charlotte Pass,294,2.442857,-3.607143,25.8

In [3]:
import pandas as pd

# Load your dataset
df = pd.read_csv(FILE)

# Compute average weather per Resort + SkiWeek across all past years
avg_weather = df.groupby(['Resort', 'SkiWeek']).agg({
    'Maximum temperature (Degree C)': 'mean',
    'Minimum temperature (Degree C)': 'mean',
    'Rainfall amount (millimetres)': 'mean'
}).reset_index()

# Add Year = 2026 for prediction
avg_weather['Year'] = 2026

# Reorder columns to match original dataset format
pred_2026 = avg_weather[['Year', 'SkiWeek', 'Resort',
                         'Maximum temperature (Degree C)',
                         'Minimum temperature (Degree C)',
                         'Rainfall amount (millimetres)']]

# Save to CSV
pred_2026.to_csv("predicted_weather_2026.csv", index=False)

In [4]:
pred_2026

,Year,SkiWeek,Resort,Maximum temperature (Degree C),Minimum temperature (Degree C),Rainfall amount (millimetres)
0,2026,1,Charlotte Pass,4.055195,-2.311039,50.554545
1,2026,2,Charlotte Pass,2.614286,-3.533766,32.136364
2,2026,3,Charlotte Pass,2.314935,-3.893506,34.536364
3,2026,4,Charlotte Pass,2.285065,-4.129221,24.536364
4,2026,5,Charlotte Pass,1.212338,-4.126623,36.563636
...,...,...,...,...,...,...
115,2026,11,Thredbo,0.896286,-3.762857,20.880000
116,2026,12,Thredbo,1.759286,-3.993381,26.920000
117,2026,13,Thredbo,3.018000,-3.407381,22.820000
118,2026,14,Thredbo,3.994184,-2.008673,21.480000
119,2026,15,Thredbo,3.024439,-2.831837,23.740000